# .github/release.yml
changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: New Features 🎉
      labels:
        - feature
        - enhancement
    - title: Bug Fixes 🐞
      labels:
        - bugfix
        - bug
        - Firefighter
        - hotfix
    - title: Internal Tools 🛠
      labels:
        - internal tools
    - title: IDE 🧮
      labels:
        - abacus
        - IDE
        - sandbox
    - title: Marketing Pages 🖥
      labels:
        - marketing
    - title: Integrations 🔗
      labels:
        - integrations
    - title: Sales 💵
      labels:
        - sales
        - Contracts
        - data
        - salesforce
    - title: Curriculum Tools 📝
      labels:
        - curriculum
    - title: Elementary 🚍
      labels:
        - elementary
    - title: Migrations 🕊
      labels:
        - migration
    - title: Other ❓
      labels:
        - "*"
