name: Add opened PRs to Code Review project

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add PR to code review project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/orgs/github-auto-tag/projects/1
          github-token: '${{ secrets.GITHUB_TOKEN }}'
